// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzutRPyv1yX7cYT8KskQifgxuVJuWUOcc',
    appId: '1:613036229728:web:953a572d4362313ec5ef05',
    messagingSenderId: '613036229728',
    projectId: 'kudosintern',
    authDomain: 'kudosintern.firebaseapp.com',
    storageBucket: 'kudosintern.appspot.com',
    databaseURL: 'https://kudosintern-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaYBXz0NygIbqDLoA9kOC0FhHFe1dUBlI',
    appId: '1:613036229728:android:89488f16746011e6c5ef05',
    messagingSenderId: '613036229728',
    projectId: 'kudosintern',
    storageBucket: 'kudosintern.appspot.com',
    databaseURL: 'https://kudosintern-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzutRPyv1yX7cYT8KskQifgxuVJuWUOcc',
    appId: '1:613036229728:web:4aae1b2316d5e1a2c5ef05',
    messagingSenderId: '613036229728',
    projectId: 'kudosintern',
    authDomain: 'kudosintern.firebaseapp.com',
    storageBucket: 'kudosintern.appspot.com',
  );
}
